package entities

const (
	addressType          = "address"
	brandType            = "brand"
	cartType             = "cart"
	cartItemType         = "cart_item"
	categoryType         = "category"
	collectionType       = "collection"
	currencyType         = "currency"
	customerType         = "customer"
	eventType            = "event"
	fileType             = "file"
	flowType             = "flow"
	fieldType            = "field"
	jobType              = "job"
	variationType        = "product-variation"
	optionType           = "option"
	orderType            = "order"
	modifierType         = "modifier"
	gatewayType          = "gateway"
	inventoryType        = "inventory"
	integrationType      = "integration"
	productType          = "product"
	promotionType        = "promotion"
	transactionType      = "transaction"
	settingsType         = "settings"
	stockTransactionType = "stock-transaction"
)
